// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"user-center/internal/config"
	"user-center/internal/repository"
	"user-center/internal/repository/cache"
	"user-center/internal/repository/dao"
	"user-center/internal/service"
	"user-center/internal/web"
	"user-center/ioc"
)

// Injectors from wire.go:

func InitWebServer(cfg *config.AppConfig, dyn config.DynamicProvider) *gin.Engine {
	cmdable := ioc.InitRedis(cfg)
	handler := ioc.InitJWTHandler(cfg, cmdable)
	v := ioc.GinMiddlewares(cfg, dyn, cmdable, handler)
	db := ioc.InitDB(cfg)
	gormUserDAO := dao.NewGORMUserDAO(db)
	redisUserCache := cache.NewRedisUserCache(cmdable)
	cachedUserRepository := repository.NewCachedUserRepository(gormUserDAO, redisUserCache)
	gormSocialAccountDAO := dao.NewGormSocialAccountDAO(db)
	socialAccountRepositoryImpl := repository.NewSocialAccountRepositoryImpl(gormSocialAccountDAO)
	transaction := ioc.InitTX(db)
	userServiceImpl := service.NewUserServiceImpl(cachedUserRepository, socialAccountRepositoryImpl, transaction)
	redisCodeCache := cache.NewRedisCodeCache(cmdable)
	cachedCodeRepository := repository.NewCachedCodeRepository(redisCodeCache)
	smsService := ioc.InitSmsService()
	smsCodeService := service.NewSMSCodeService(cachedCodeRepository, smsService)
	userHandler := web.NewUserHandler(userServiceImpl, smsCodeService, handler)
	wechatService := ioc.InitWechatService(cfg)
	oAuth2WechatHandler := ioc.InitOAuth2WechatHandler(cfg, wechatService, userServiceImpl, handler)
	engine := ioc.InitWebServer(cfg, dyn, v, userHandler, oAuth2WechatHandler)
	return engine
}
