// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"user-center/internal/repository"
	"user-center/internal/repository/cache"
	"user-center/internal/repository/dao"
	"user-center/internal/service"
	"user-center/internal/web"
	"user-center/ioc"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := ioc.InitRedis()
	v := ioc.GinMiddlwares(cmdable)
	db := ioc.InitDB()
	gormUserDAO := dao.NewGORMUserDAO(db)
	redisUserCache := cache.NewRedisUserCache(cmdable)
	cachedUserRepository := repository.NewCachedUserRepository(gormUserDAO, redisUserCache)
	gormSocialAccountDAO := dao.NewGormSocialAccountDAO(db)
	socialAccountRepositoryImpl := repository.NewSocialAccountRepositoryImpl(gormSocialAccountDAO)
	transaction := ioc.InitTX(db)
	userServiceImpl := service.NewUserServiceImpl(cachedUserRepository, socialAccountRepositoryImpl, transaction)
	redisCodeCache := cache.NewRedisCodeCache(cmdable)
	cachedCodeRepository := repository.NewCachedCodeRepository(redisCodeCache)
	smsService := ioc.InitSmsService()
	smsCodeService := service.NewSMSCodeService(cachedCodeRepository, smsService)
	userHandler := web.NewUserHandler(userServiceImpl, smsCodeService)
	wechatService := ioc.InitWechatService()
	oAuth2WechatHandler := web.NewOAuth2WechatHandler(wechatService, userServiceImpl)
	engine := ioc.InitWebServer(v, userHandler, oAuth2WechatHandler)
	return engine
}
