// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"user-center/internal/config"
	"user-center/internal/repository"
	"user-center/internal/repository/cache"
	"user-center/internal/repository/dao"
	"user-center/internal/service"
	"user-center/internal/web"
	"user-center/ioc"
	"user-center/pkg/logger"
)

// Injectors from wire.go:

func InitWebServer(cfg *config.AppConfig, dyn config.DynamicProvider, l logger.Logger) *gin.Engine {
	cmdable := ioc.InitRedis(cfg)
	handler := ioc.InitJWTHandler(cfg, cmdable)
	v := ioc.GinMiddlewares(cfg, dyn, cmdable, handler, l)
	db := ioc.InitDB(cfg)
	gormUserDAO := dao.NewGORMUserDAO(db)
	redisUserCache := cache.NewRedisUserCache(cmdable)
	cachedUserRepository := repository.NewCachedUserRepository(gormUserDAO, redisUserCache)
	gormSocialAccountDAO := dao.NewGormSocialAccountDAO(db)
	socialAccountRepositoryImpl := repository.NewSocialAccountRepositoryImpl(gormSocialAccountDAO)
	transaction := ioc.InitTX(db)
	gormEventOutboxDAO := dao.NewGORMEventOutboxDAO(db)
	eventOutboxRepositoryImpl := repository.NewEventOutboxRepositoryImpl(gormEventOutboxDAO)
	publisher := ioc.InitEventPublisher(cfg, eventOutboxRepositoryImpl, l)
	userServiceImpl := service.NewUserServiceImpl(cachedUserRepository, socialAccountRepositoryImpl, transaction, publisher, l)
	redisCodeCache := cache.NewRedisCodeCache(cmdable)
	cachedCodeRepository := repository.NewCachedCodeRepository(redisCodeCache)
	smsService := ioc.InitSmsService(l)
	smsCodeService := service.NewSMSCodeService(cachedCodeRepository, smsService)
	userHandler := web.NewUserHandler(userServiceImpl, smsCodeService, handler)
	wechatService := ioc.InitWechatService(cfg)
	oAuth2WechatHandler := ioc.InitOAuth2WechatHandler(cfg, wechatService, userServiceImpl, handler)
	gormSignInDAO := dao.NewGORMSignInDAO(db)
	redisSignInCache := cache.NewRedisSignInCache(cmdable)
	signInRepositoryImpl := repository.NewSignInRepositoryImpl(gormSignInDAO, redisSignInCache)
	gormPointDAO := dao.NewGORMPointDAO(db)
	pointRepositoryImpl := repository.NewPointRepositoryImpl(gormPointDAO)
	redisRankCache := cache.NewRedisRankCache(cmdable)
	rankRepositoryImpl := repository.NewRankRepositoryImpl(redisRankCache)
	redisActivityLogRepository := repository.NewRedisActivityLogRepository(cmdable)
	signInServiceImpl := service.NewSignInService(signInRepositoryImpl, pointRepositoryImpl, rankRepositoryImpl, redisActivityLogRepository, transaction, publisher, l)
	checkInHandler := web.NewCheckInHandler(signInServiceImpl)
	rankServiceImpl := service.NewRankServiceImpl(rankRepositoryImpl, cachedUserRepository)
	rankHandler := web.NewRankHandler(rankServiceImpl)
	engine := ioc.InitWebServer(cfg, v, userHandler, oAuth2WechatHandler, checkInHandler, rankHandler)
	return engine
}
